//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreOAIPexam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discounts
    {
        public Discounts()
        {
            this.Sale_Auto = new HashSet<Sale_Auto>();
        }
    
        public int id_discount { get; set; }
        public string type { get; set; }
        public int value___ { get; set; }
    
        public virtual ICollection<Sale_Auto> Sale_Auto { get; set; }
    }
}
