//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreOAIPexam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AudiDodelat_33__33__33__33__33__33__33Entities1 : DbContext
    {
        public AudiDodelat_33__33__33__33__33__33__33Entities1()
            : base("name=AudiDodelat_33__33__33__33__33__33__33Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Auto> Auto { get; set; }
        public DbSet<Discounts> Discounts { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Position> Position { get; set; }
        public DbSet<Sale_Auto> Sale_Auto { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; } //Именование класса с маленькой буквы
        public DbSet<users> users { get; set; } //Именование класса с маленькой буквы
    }
}
