//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreOAIPexam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int id_position { get; set; }
        public string name { get; set; }
        public Nullable<decimal> Oklad { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
